
# A cluster with two managed nodegroups
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: effulgencetech-cluster
  region: us-west-2
  
vpc:
  subnets:
    private:
      us-west-2a: { id: subnet-0ff156e0c4a6d300c }
      us-west-2b: { id: subnet-0549cdab573695c03 }
      us-west-2c: { id: subnet-0426fb4a607393184 }

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 4
    ami: ami-0e124de4755b2734d
    desiredCapacity: 3
    volumeName: /dev/xvda
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

  - name: managed-ng-2
    instanceType: t2.medium
    minSize: 2
    maxSize: 3
