---
apiVersion: v1
kind: Pod
metadata:
  name: effulgence-pod
  labels:
    app: webapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP